name: AWS Code Build
on: [push]
jobs:
  BuildWebJob:
    runs-on: codebuild-VAMS-BuildAndDeploy-${{ github.run_id }}-${{ github.run_attempt }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          path: ./vams

      - name: Setup node for the whole package
        uses: actions/setup-node@v3

      - name: Yarn Install
        uses: Borales/actions-yarn@v4.2.0
        with:
            dir: "vams/web"
            cmd: install

      - name: Web build
        working-directory: vams/web
        env:
          CI: ""
        run: npm run build.lowmem

      - name: Npm install infrastructure directory
        working-directory: vams/infra
        run: npm install

      - name: Synthesize Cloudformation templates
        working-directory: vams/infra
        run: |
            CDK_NAG_ENABLED=false
            export STACK_NAME=dev
            export REGION=us-west-2
            npx cdk synth --context adminEmailAddress=$ADMIN_EMAIL
